[package]
name = "vm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
bitflags = "1.3"
crossterm = "0.22"
gramatika = { path = "../../../../../gramatika/crates/gramatika" }
itertools = "0.10"
lazy_static = "1.4"
macro_utils = { path = "../macro-utils" }
nu-ansi-term = "0.38"
num-traits = "0.2"
num-derive = "0.3"
once_cell = "1.8"
parking_lot = "0.11"
rustc-hash = "1"
strip-ansi-escapes = "0.1"
terminal_size = "0.1"
